name: Build

env:
  JAVA_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC"
  GRADLE_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC"
  TERM: xterm-256color
  JDK_CURRENT: 11
  PRIVATE_REPO_TOKEN: ${{ github.token }} 


on: 
  workflow_dispatch:
        inputs:
                feature:
                        required: true
                        type: string
                        description: add tag for unique build
                s3publish:
                        required: false
                        type: boolean
                        description: publish to S3 bucket
                        default: false
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}
  build:
    needs: cancel-previous-runs
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: 'temurin'
      - name: Build
        run: ./gradlew clean build
      - name: Build Imprivata CAS
        run: ./post-build.sh
#      - uses: actions/upload-artifact@v4.0.0
#        name: Upload original CAS build for Imprivata
#        with:
#                name: cas-original-build
#                path: build/libs/
      - name: set name package
        run: |
                echo "GITHUB_RELEASE_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: get CAS version
        run: |
                echo "GITHUB_CAS_VERSION=$(./gradlew -q casVersion)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4.0.0
        name: Upload Imprivata package
        with:
                name: pam-cas.${{env.GITHUB_CAS_VERSION}}.${{env.GITHUB_RELEASE_DATE}}.${{inputs.feature}}
                path: ./**/pkg/*
      - name: Create archive
        run: zip -r pam-cas.${{env.GITHUB_CAS_VERSION}}.${{env.GITHUB_RELEASE_DATE}}.${{inputs.feature}}.zip pkg
      - name: list
        run: ls -al
  #    - name: Publish to S3 bucket
  #      if: ${{inputs.s3publish == true}}
  #      uses: shallwefootball/s3-upload-action@master
  #      with:
  #        aws_key_id: ${{ secrets.AWS_KEY_ID }}
  #        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  #        aws_bucket: ${{ secrets.AWS_BUCKET }}
  #        source_dir: ./pam-cas.${{env.GITHUB_CAS_VERSION}}.${{env.GITHUB_RELEASE_DATE}}.${{inputs.feature}}.zip
  #        destination_dir: /legacy/tmp/
      - name: Upload binary to S3 bucket
        uses: NayamAmarshe/cp-file-to-s3@master
        with:
         args: --acl public-read
         env:
         FILE: ./pam-cas.${{env.GITHUB_CAS_VERSION}}.${{env.GITHUB_RELEASE_DATE}}.${{inputs.feature}}.zip
         DEST: legacy/tmp/
         AWS_REGION: 'us-east-2'
         AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        
                
            
      
      
  
      
        
        
