name: Build

env:
  JAVA_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC"
  GRADLE_OPTS: "-Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC"
  TERM: xterm-256color
  JDK_CURRENT: 11
  PRIVATE_REPO_TOKEN: ${{ github.token }} 


on: workflow_dispatch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}
  build:
    needs: cancel-previous-runs
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: 'temurin'
      - name: Build
        run: ./gradlew clean build
      - uses: actions/upload-artifact@v4.0.0
        with:
                name: cas-original-build
                path: build/libs/
